.github/workflows/cd.yml
.github/workflows/ci.yml
dockerfiles/Dockerfile.ci
dockerfiles/Dockerfile.kicad
src/atopile/cli/build.py
src/atopile/cli/cli.py
src/atopile/cli/common.py
src/atopile/cli/install.py
src/atopile/config.py
src/atopile/manufacturing_data.py

- Support multiple boards for the same project
- Make CI on the user-side easier
See: https://toil.kitemaker.co/2hAmxC-atopile/dSlNKj-atopile/items/48
- Add `mfg-data` target which controls the KiCAD CLI
- Supports multiple builds with varying entry-points
- Add a `-v` / `--verbose` option to the CLI, allowing users to say `-v` or `-vv` for increaing logging verbosity. This replaces `--debug`
- `--debug` option now starts a `debugpy` session and waits for connection
- Add `atopile-kicad` container which installs both, and has an easy-to-use entry point for CI 
- Build targets now receive a `BuildContext` object containing data they'd otherwise need to infer or derive from the config/cli/etc... individually
I used the logic-card project to smoke the changes: …

Refactor config + project ingestion

---

src/atopile/cli/common.py
src/atopile/config.py
tests/test_config.py

Improve error in case of a build that doesn't exist

---

src/atopile/config.py

It looks like the error message was meant to reference the other variable. Underlying problem (detecting `_autosave-*` and `~_autosave-*`) will still exist.

Resolve incorrect reference in build context error message

---

src/atopile/cli/install.py

Return early in case of missing semver tags

---

src/atopile/manufacturing_data.py

Make the "{{GITHASH}}" stamp on the boards "dirty" if the repo is dirty at build time.
This should only happen locally

Githash should be question marks for dirty git-hashes

---

src/atopile/errors.py

Seems like at least in one place the error raised is returning objects which are not str : Example:  atopile/parse.py line101 raise AtoFileNotFoundError(src_path) src_path here is actually Path

Ensure the message is str

---

src/atopile/cli/create.py
src/atopile/cli/install.py

Small refactor of ato install, was having problems with click.
now at the very end of ato create we run a bare 'ato install'
There might be a better way to handle the paths here, but this seems to be functional.

installs generics after running ato create automatically

---

src/atopile/components.py

Was using strip(".kicad_mod") on the footprint file names from firebase, changed to use:
footprint = footprint.removesuffix(".kicad_mod")

strip did not do what I thought it did, whoops

---

README.md

Github doesn't yet support ato, but based on your code syntax it appears to be more heavily based on python. 
This change simply switching to the python syntax. But later on if you are more established and github adds support, you can switch from python to ato syntax highlights
```python
import Resistor from "generics/resistors.ato"
module VoltageDivider:
signal top
signal out
signal bottom
r_top = new Resistor
r_top.footprint = "R0402"
r_top.value = 100kohm +/- 10%
r_bottom = new Resistor
r_bottom.footprint = "R0402"
r_top.value = 200kohm +/- 10%
top ~ r_top.p1; r_top.p2 ~ out
out ~ r_bottom.p1; r_bottom.p2 ~ bottom
import RP2040Kit from "rp2040/rp2040_kit.ato"
import LEDIndicator from "generics/leds.ato"
import LDOReg3V3 from "regulators/regulators.ato"
import USBCConn from …
```

Syntax highlight hack as github doesn't support ato syntax yet

---

src/atopile/manufacturing_data.py

By default [GitPython](https://gitpython.readthedocs.io/en/stable/index.html) does not search parent directories for the Git root.
See [Changelog — GitPython 3.1.42 documentation](https://gitpython.readthedocs.io/en/stable/changes.html#id80)
> Repo(path) will not automatically search upstream anymore and find any git directory on its way up. If you need that behaviour, you can turn it back on using the new search_parent_directories=True flag when constructing a Repo object.
This change means that if an atopile project is in a sub-directory of a main project, when `ato build` is run in that sub-directory, ato will be able to obtain the Git hash by searching up the directory tree.

Search parent directories for Git root

---

src/atopile/expressions.py

Two things fixed here:
If `max_decimals` was not given, the percentage shown was incorrect. 03a3a1c5f320c9195d3c96d2ea96058d1423badb
More importantly, there was a crash when printing a zero ohm resistor (`tolerance_pct is None`) which is now fixed. 513fc9c6152af3d6d570d0ad25f41e6a32e0ba88
Now, the values without tolerances defined don't have this "+/- 0 (0%)" after the value, but the behavior still seems correct for values with tolerances:

Expressions: Tolerance printing fixes

---

src/atopile/instance_methods.py
src/atopile/layout.py
tests/test_instance_methods.py

Improve robustness of simultaneous descent in layout module - fixes #237

---

src/vscode-atopile/package.json
src/vscode-atopile/snippets/snippets.json
src/vscode-atopile/src/ui/ui.ts

Removes dependence on `atopile.interpreter` in extension UI. UI will now rely on the Python UI being set within VS Code.

Python venv settings for UI extension

---

src/vscode-atopile/package-lock.json
src/vscode-atopile/package.json

Reverts atopile/atopile#244 due to the failed CI job: https://github.com/atopile/atopile/actions/runs/8351119738/job/22858890844

Revert "Bump @typescript-eslint/parser from 6.17.0 to 7.2.0 in /src/vscode-atopile"

---

src/atopile/kicad_plugin/common.py
src/atopile/kicad_plugin/pullgroup.py

Keeps groups static when using pull group kicad plugin
- Calculates anchor component in group based on pin count (component area tie breaker)
- Calculates source vector from origin
- Calculates target vector from origin
- Applied target_vector - source_vector translation to entire group after all layout info is updated to source positions

Pull group plugin movement fix

---

src/atopile/kicad_plugin/common.py
src/atopile/kicad_plugin/pullgroup.py
src/atopile/kicad_plugin/pushgroup.py

Fixes pushgroup bug in `sync_tracks`
- After duplicating track from source board, ghost track remains on source board/group
- Doesnt happen in pull because source board is closed and not saved
- Exponentially adds tacks to source and target after multiple pushes
- Solved by removing ghost track from source board after duplication
Overloaded `find_anchor_footprint` function to allow board/group interchangability for both push/pull
Fix #213
- Copies over reference designator relative position to footprint
- Copies attributes(thickness, width, height, rotation)

Fix pushgroup bug and ref designators

---

src/atopile/kicad_plugin/common.py
src/atopile/kicad_plugin/pullgroup.py

Fix #216 
**This deserves a thorough squiz**, seems hacky but setting zone net was tricky. **There must be a cleaner way to map source netname to target netname.**
- Duplicates source zone to target board
- Updates the net of the zone to new net name on target board
- Finds net name of source zone
- iterates thru source footprint pads until netname match is found
- uses matched footprint uuid and uuid map to find target footprint
- uses matched pad index of matched footprint to get new net information
- Sets zone net to target net info
- Sets zone to netcode 0 if no match found (no net)

Zone copy with net

---

src/atopile/cli/configure.py

Tiny PR - 1 character
The kicad plugin script `atopile.py` plugin_path is created with backslashes, this is no bueno for windows.
Switching to raw string fixed for windows, should work on unix.
Will this happen elsewhere?

Windows path fix

---

src/atopile/viewer/src/App.tsx
src/atopile/viewer/src/CustomEdge.tsx
src/atopile/viewer_utils.py

Provide more clarity on what links without having to click on them:

Add list of link names to viewer links

---

src/atopile/assertions.py
src/atopile/expressions.py
src/atopile/front_end.py
tests/test_expressions/test_ranged_values.py

We've:
- Re-added the assertions table (instead of logging only in case of failure)
- Formatted the ranged values better; either as the source code dictates, or a little more intelligently if we're guessing otherwise
Closes #329

Assertions table is back! + unit formatting sucks less

---

src/atopile/front_end.py
tests/test_front_end/test_atoms.py

Before this, `50 +/- 10V` was incorrectly read as `60V to 60V`.

Fix un-unit'ed bilateral tolerances

---

src/atopile/expressions.py

This assertion previously triggered when any constant was additionally set from the "context" variable, but that failed to consider that the constants were incorporated into the sub-context passed to the next lambda.
https://github.com/atopile/bikey-wagon/pull/4 builds with this change without forcing discrete values around! 🥳
Thank you @jarrod89 🙌

Loosen overwritten constant complaint

---

src/atopile/kicad6.j2

If a component has no pins, the generated netlist would include a spare `)` that made it invalid.

Fix netlist generation for components that have no pins

---

src/atopile/components.py
src/atopile/kicad_plugin/common.py

I was seeing a generic inductor get resolved to a component with `"footprint": {"kicad": "L"}`, this is a hack to try to recover from these cases.

More robust footprint inference for generic components

---

src/atopile/bom.py

This makes it easier on the BOM matching workflows of JLCPCB et al.

Use MPN instead of ? in BOM generation

---

pyproject.toml
src/faebryk/libs/picker/lcsc.py
src/faebryk/tools/libadd.py

Switches to our fork of easyeda2kicad, which includes enhancements not yet available upstream.

Fix: Support EasyEDA symbols with multiple units

---

src/faebryk/exporters/netlist/graph.py
src/faebryk/library/Net.py
src/faebryk/libs/library/L.py
test/exporters/netlist/test_graph.py

Example names from the `mcu` example:
```
*6198-hv-0
*6198-hv-1
*6198-hv-2
*6198.led.led-net
*6198.mcu-net-0
*6198.mcu-net-1
*6198.mcu-net-2
*6198.mcu-net-3
*6198.mcu-net-4
*6198.mcu-net-5
*6198.mcu-net-6
*6198.mcu-net-7
*6198.mcu-net-8
*6198.mcu-signal-0
*6198.mcu-signal-1
*6198.mcu.boot_selector-net
*6198.mcu.clock_source-net
*6198.mcu.clock_source.crystal.footprint.pins[1].net-net
*6198.mcu.ldo-signal
*6198.mcu.ldo.footprint.pins[3].net-net
*6198.mcu.rp2040-net-0
*6198.mcu.rp2040-net-1
*6198.mcu.rp2040-net-2
*6198.mcu.rp2040-signal
*6198.usb_power-net-0
*6198.usb_power-net-1
*6198.usb_power-net-2
*6198.usb_power-net-3
*6198.usb_power-signal-0
*6198.usb_power-signal-1
factory_test_enable
io[0]
io[10]
io[11]
io[12]
io[13]
io[14]
io[15]
io[16]
io[17]
io[18]
io[19]
io[1]
io[20]
io[21] …
```

Improve default net naming algorithm

---

src/faebryk/libs/kicad/fileformats.py

Fix: Fileformats: Decode .kicad_pcb files with unnamed zone entries

---

src/atopile/cli/build.py

Temporary measure to get CI checks passing for Python projects, until we re-introduce `.ato` support.

CLI: Skip ato builds

---

.github/workflows/pytest.yml

`pytest` was failing ~50% of the time in CI because there was a collision trying to build the core from multiple processes.
This fixes that, by ensuring that `pytest` is run from a non-editable install of atopile

Fix `pytest` CI stability

---

.github/workflows/pytest.yml
pyproject.toml
uv.lock

Uses the `[dependency-groups]` to support `uv` properly
Remove test group. Who uses it? Couldn't find a good case )(for now)

uv sync --dev should install all dev dependencies

---

examples/project/ato.yaml
test/common/resources/test-project/ato.yaml

Commit is tagged as `v0.3.1-dev0`
I would've made it `v0.3.0-dev0`, but that already exists
I would've made it `v0.3.0-dev1`, but `hatch-vcs` doesn't support it
Need to reinstall atopile after pulling this
`uv sync --dev` is sufficent

Up-rev requirements for v0.3.1 release

---

src/faebryk/library/Ethernet.py
src/faebryk/library/HDMI.py
src/faebryk/library/I2S.py
src/faebryk/library/_F.py

Lib: Add i2s, Gigabit Ethernet and HDMI interfaces
Adding interfaces used in NONOS project for CM4, should be generally useful!

Add module interfaces for Ethernet (4 pair), HDMI and I2S

---

src/faebryk/library/has_pin_association_heuristic_lookup_table.py

Don't warn if a pin is unmatched if it's contained in NC for `has_pin_association_heuristic_lookup_table`

Fix: Library: Don't warn if unmatched pin in NC

---

uv.lock

Update dependency to remove 3d model warning

Fix: Deps: Remove no 3d model warning

---

.github/workflows/regression.yml

If [I'm reading this](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target) right, workflow should now trigger on: opening, pushes or adding a label

Trigger regression on adding a label to it's PR

---

src/faebryk/library/LDO.py
src/faebryk/libs/picker/api/api.py
src/faebryk/libs/picker/api/common.py
src/faebryk/libs/picker/api/picker_lib.py
src/faebryk/libs/picker/jlcpcb/jlcpcb.py
src/faebryk/libs/picker/lcsc.py
src/faebryk/libs/picker/picker.py
src/faebryk/libs/util.py

- Pick single candidate modules first
- Try non-singles in one go 
- only consider attachable modules/parts
- cache/deduplicate api requests

Picker: Add heuristics for speedup

---

src/atopile/_shim.py
src/atopile/front_end.py

- Fix signal de-duplication
- Implement cumulative operators

Make `ato` build again - Part V: The Emprire Strikes Back

---

src/atopile/buildutil.py

`output_base` is a stem of a path, not a directory

Fix variable report location

---

src/faebryk/core/parameter.py
src/faebryk/libs/picker/api/api.py
src/faebryk/libs/sets/quantity_sets.py

Use `@once` in some expensive functions that are called often
> `FBRK_PICKER_API_URL=http://localhost:8000 python ./test/runtest.py  -k test_very_compl`
Before
```
Timings                                                                                                        
┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━┓                                                                                       
┃ Category           ┃ Subcategory ┃   Value ┃                                     
Unit ┃                                                                                                                       
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━┩                                                                                       
│ construct          │ …
```

Core; Some micro-optimization of p_sets

---

src/atopile/_shim.py
src/faebryk/core/node.py
src/faebryk/exporters/netlist/graph.py
src/faebryk/exporters/pcb/kicad/pcb.py
src/faebryk/library/ElectricPower.py
src/faebryk/library/_F.py
src/faebryk/library/has_net_name.py
test/core/test_node.py
test/exporters/netlist/test_graph.py

These tools are implemented in `v0.2` via the `.override_net_name` attr
Additionally, it adds the "suggested" net name as requested @napowderly

Add tools to override net names

---

.github/workflows/wheels.yml

Failure seen in: https://github.com/atopile/atopile/actions/runs/12564201707/job/35027048579
Fixes spurious dependency on repository contents introduced in #616. Python doesn't seem to be required by any subsequent steps.

Fix PyPI publish failure due to missing `pyproject.toml`

---

src/faebryk/libs/sets/quantity_sets.py
uv.lock

- Ensure consistent behavior between __mul__ and __rmul__
- Add ParameterOperatable checks to all operator methods
- Create helper method for parameter operability checks
- Maintain type safety while allowing operator fallback

fix: standardize quantity operator precedence

---

pyproject.toml

Use packaged `atopile-easyeda2kicad` instead of repo install, so we can deploy atopile to pypi

Use packaged `atopile-easyeda2kicad`

---

pyproject.toml

Now the version string is just `major.minor.patch`/`.dev0`
This helps us with `uv` lock stability, but without auto-incrementing the `.dev` distance, auto-deployments to test pypi won't go as often as I'd like

Stabilise version

---

src/atopile/cli/build.py
src/faebryk/libs/picker/lcsc.py

This works for now, but as stated in the [TODO](https://github.com/atopile/atopile/blob/a0a8acc6358c0ff7629fa581248b0fdbd4bd8f0e/src/atopile/cli/build.py#L91), should use buildcontext instead.
Fixes #712 

Fix footprint 3D file path

---

src/faebryk/library/CH342F.py
src/faebryk/library/CH344.py
src/faebryk/library/CH344Q_ReferenceDesign.py
src/faebryk/library/EnablePin.py
src/faebryk/library/WCHJiangsu_Qin_Heng_CH224K.py
src/faebryk/library/WCHJiangsu_Qin_Heng_CH224K_ReferenceDesign.py

Also fix reversed resistor values in one module

Bugfix: faebryk: Library: Set weak owner

---

src/faebryk/exporters/pcb/kicad/pcb.py
src/faebryk/libs/util.py
test/libs/util/test_yield_missing.py

Pads were not having rotation re-applied when reloaded by ato
Net re-numbering will now find next available number, avoiding duplicates.

fix net numbering and pad rotations

---

src/faebryk/library/EnablePin.py

Bugfix: Library: EnablePin: Return resistor when using set_weak

---

.github/workflows/pytest.yml

Pytest is not reporting as the email and password is missing from the enviroment variables, copying from regressions.yml where this is working.

Add credentials env variables for pytest history db reporting

---

src/atopile/front_end.py
src/faebryk/exporters/pcb/kicad/transformer.py

This relinks v0.2 designs neatly, but carries some tech debt, as mentioned in https://github.com/atopile/atopile/issues/838#issuecomment-2599315558
This needs to be resolved more thoroughly mid-term, since this won't work (at least well) for `fabll` modules, but I see no clean way outta it right now.
Fixes: #838

Handle specialization in `ato` the same as v0.2

---

src/atopile/buildutil.py
src/faebryk/exporters/pcb/kicad/transformer.py

It was causing cycles where it'd remove something from the pcb's "footprints" list, but it'd still be linked via a trait. This means it wouldn't be output on rebuild, then it'd be re-added on the next run. This caused cycling where components wouldn't appear every second run under some circumstances
Fixes: #846

Remove cleanup from PCB transformer and buildutil

---

src/atopile/buildutil.py
src/atopile/cli/cli.py
src/atopile/layout.py

Add 4 space indentation as used in python (PEP8) for consistency. 
This make the json files human readable
**_Note: idk if you want to format all json files, and if they all should be 4 space indentation_**

Feature: Add formatting of user visible json files

---

src/atopile/layout.py

Update module layout indexing to use the absolute entry file path when looking up ato modules, ensuring correct module identification during the build process.

Fix module layout indexing with absolute entry file path

---

src/atopile/cli/create.py
src/atopile/cli/install.py

Link generics by default on install.
Change option for vendoring to `--vendor`
Install generics by default on `ato create`

Update `ato install`

---

src/atopile/config.py

- Enhance layout path resolution in BuildTargetPaths
- Add docstrings for entry file path and section properties
- Simplify layout path initialization with more flexible path handling
This means something like this works:
```yaml
ato-version: ^0.2.0
builds:
default:
entry: elec/src/hil-blocks.ato:HilBlocks
lv2842kit:
entry: elec/src/components/lv2842xlvddcr/elec/src/lv2842kit.ato:LV2842Kit
paths:
layout: elec/src/components/lv2842xlvddcr/elec/layout/default/LV2842Kit.kicad_pcb
dependencies:
- generics
```

Improve build target paths configuration handling

---

src/atopile/cli/build.py

Previously, this would only work on projects with a single build configuration, because the way we were assessing the selected builds didn't make sense.

Fix  `--open` option

---

src/faebryk/libs/app/erc.py

Power ERC short check currently passes a power interface to the ercfault short exception handler, should pass hv and lv.

fix error message for ERC short

---

src/faebryk/libs/kicad/fileformats.py
src/faebryk/libs/sexp/dataclass_sexp.py
test/libs/kicad/test_fileformats.py
test/libs/kicad/test_sexp.py

I've managed to replicate this one and think it's actually a subtly different cause; it's a fault in the `CatchAll` and sexp de/encoder that's moving a positional `(island)` from slot 1 to the end.
I think there are three issues:
1. The positional `(island)` isn't being parsed properly
2. The decoder isn't properly rejecting additional statements without 
3. The `CatchAll` isn't re-placing values back in their correct indices
Fixes #776 

Fix `(island)` zones sexp decoding, `CatchAll` and `CatchAll` reproduction sequence

---

src/faebryk/library/has_simple_value_representation_based_on_params_chain.py

Failing build because `has_simple_value_representation_based_on_params_chain` was expecting all parameters to provide a value back to construct the 'value' property in the KiCAD component. In my case, an electrolytic capacitor did not have a temp-co property, so the whole build would fail. 
Now, they get value is wrapped in a try-except block and returns an empty string for parameters that we fail to get a value for.

Add try except block to get_value in has_simple_value_representation

---

src/faebryk/core/parameter.py
src/faebryk/core/solver/mutator.py
test/core/solver/test_solver.py

Allows to do this:
```
A, B = times(2, Parameter)
A.constrain_mapping(B, {5: Range(10, 100), 10: Range(500, 1000))
```
This creates under the hood a constrained implication per mapping case.
Very useful for configuration resistors etc.

Core: Solver add param mapping constraint

---

src/faebryk/library/KicadFootprint.py

From: https://github.com/atopile/faebryk/pull/39
Co-authored-by: @mawildoer

Library: KicadFootprint: Add ValueError for kicad identifier

---

src/atopile/attributes.py
src/atopile/front_end.py

This remains incomplete, because `has_single_electric_reference` provides no mechanism for `ato` to readily get the reference. I believe this needs to be addressed considering https://github.com/atopile/atopile/discussions/921

Add `gnd` shim to `I2C`

---

src/atopile/config.py

This worked before when you pointed at the root dir, but not when code was in a subdirectory.
We're now searching parents for the `ato.yaml` config file as well

Fix #935 - `ato build <entry addr>`

---

src/faebryk/library/Regulator.py
src/faebryk/library/_F.py
src/faebryk/library/regulators.ato

Produces an error when two power supply outputs are connected directly to eachother

add regulator type to fabll lib to define power sink/source

---

src/atopile/attributes.py

When a user made an error with package size (in my case not including a prefix to the number), the error used to indicate that it was a bad parameter without suggesting correct options for package. Was due to a comma turning second portion of string into second argument rather than concatinating

fixed 'bad parameter' error output

---

src/faebryk/library/OpAmp.py

Added Vcc+ to hv heuristic lookup and Vcc- to lv heuristic lookup to allign with JLCPCB pinmapping for select OpAmps

OpAmp changes, heuristic pin lookup addition

---

src/faebryk/libs/util.py

Fixes `JsonDecodeError` when installed from a wheel.

Fix: Libs: assume not an editable install if dist info not available

---

test/test_regressions.py

- Increase instrumentation interval for profiling to 10ms (from 1ms)
- Remove environment-specific parameters from test_projects

Simplify regression test project builds

---

src/faebryk/library/resistors.ato

.value no longer supported in std library parts, need to use .resistance instead

updated .value to .resistance

---

src/faebryk/core/parameter.py
src/faebryk/core/solver/analytical.py
src/faebryk/core/solver/canonical.py
src/faebryk/core/solver/defaultsolver.py
src/faebryk/core/solver/mutator.py
src/faebryk/core/solver/utils.py
src/faebryk/library/Crystal_Oscillator.py
src/faebryk/libs/logging.py
src/faebryk/libs/sets/numeric_sets.py
src/faebryk/libs/util.py
test/core/solver/test_literal_folding.py
test/core/solver/test_solver.py
test/libs/test_sets.py

- configurable console width
- cache compact_repr calls for better perf
- check for none operands in expression
- split out `is_uncorrelatable_literal`
- add `is_congruent_to_factory` as helper
- `check_constrained` flag for congruency check
- fix: check for correlations in pos_congruent
- better printing of infix exprs with lit suffix
- split canonical pred out algo out
- from_ops fold alias/ss
- unique rows print
- cleanup graph logging from ss/is lits
- lits: rel round base code (not in use yet)
- add soft_replace in mutator
- fix alias_lit and subset_lit duplicate detection
- fix ss estimation for logic
- scope singleton alias
- included created in output
- fix ops created in wrong graphs
- more duplicate expr detection
- revert broken mutated_since_last check
- try_extract checks old …

Core: Solver: More literal folding 2

---

src/atopile/buildutil.py

to get large boards to build, both parameter solving and bus params resolution must be disabled, this is a hack to be able to get HIL to build in CI.

skip bus parameter resolution if skip solving is enabled

---

examples/ch1_2_good_voltage_divider.ato

Two changes are fixed:
- `in.current` → `in.max_current`, otherwise it fails with an error about a not-forward-declared variable.
- `>` → `>=`, otherwise it shows a warning:
```
WARNING  Not Implemented Error                                                                                                                      
> is not supported. Use >= instead.                                                                                                        
```

Fix example in docs tutorial

---

src/faebryk/exporters/pcb/kicad/transformer.py

Add functionality in the KiCad PCB transformer to hide all designators.
Fixes https://github.com/atopile/atopile/issues/1008

Faebryk: exporters: PCB: KiCad: Add `hide_all_designators()` method

---

src/faebryk/libs/kicad/fileformats.py

Text was not having its visibility setting preserved between builds, which was kind of maddening.

Preserve fp_text hide property

---

src/faebryk/core/moduleinterface.py
src/faebryk/library/ResistorVoltageDivider.py
src/faebryk/library/USB2514B_ReferenceDesign.py
src/faebryk/library/_F.py
src/faebryk/library/regulators.ato
src/faebryk/library/vdivs.ato
src/faebryk/libs/sets/quantity_sets.py
test/core/solver/test_solver.py
test/front_end/test_front_end_pick.py
test/libs/picker/test_pickers.py

- Unified voltaged dividers in Fabll and ato with the base definition in ResistorVoltageDivider.py
- Reordered equations a to work within current solver capabilities
- Adds MIFs as a type that can be used in connect_via, helpful to add a connection in-between two components.
- Adds several tests for Vdiv solving

Fix Voltage dividers

---

.github/dependabot.yml

Updates dependabot config to enable the `uv` updater.
Caveats:
- requires beta flag
- doesn't yet look at `uv.lock`
- or dependency groups in `pyproject.toml`

Meta: Enable dependabot for `uv`

---

.github/workflows/deploy.yml
.github/workflows/regression.yml
.github/workflows/vsx.yml
.github/workflows/website.yml
uv.lock

- Update UV in all workflows
- Upgrade UV in lockfile to 0.6.4
- Run uv lock --upgrade

Deps: Update UV and lockfile

---

src/faebryk/exporters/bom/jlcpcb.py
src/faebryk/library/_F.py
src/faebryk/library/has_explicit_part.py
src/faebryk/libs/app/pcb.py
test/exporters/bom/test_bom.py
test/runtest.py

Adds way to specify overriden footprint when specifying explicit part.
Useful for parts without fp data in lcsc.
Also:
- Add tests for bom output

BoM: Easier way to specify fp overrride for explicit part

---

src/faebryk/core/solver/mutator.py
src/faebryk/libs/util.py

Fixes rounding error when comparing literals. Previously we were comparing hashes of the two numbers, now we use the equals operator.

Core: Solver: Fix finding duplicates by hash generating spurious contradictions

---

src/faebryk/exporters/parameters/parameters_to_file.py

Variable names were being overwritten in the report when you had more than one component with the same name (at lowest level).
Now uses full name.

Use full name for variable report to avoid overwritting

---

src/atopile/attributes.py

provides a way to softly set a net name in ato
Future upgrade:
- Prioritize suggested name based on project hierarchy (see below)
- Prefix suggested names with source id when there are conflicts, eg cell_1_gnd instead of gnd_8

add setter/getter for suggested_net_name in ato

---

src/faebryk/libs/app/erc.py
test/library/nodes/test_electricpower.py

Don't trigger if there is 1 power source

Bug: ERC: power_source short check

---

src/atopile/cli/cli.py
src/atopile/cli/create.py
src/atopile/config.py
src/atopile/errors.py

Before:
After:
Also enables Typer's `rich_markup_mode`, to render newlines in `ato create` help text.

CLI: Fix error when creating component outside of project directory

---

src/atopile/config.py
src/faebryk/library/regulators.ato

Much cleaner output of build artifacts.

Split build targets into their own directory

---

examples/ch2_1_fab.py
src/faebryk/core/solver/mutator.py

When solver doesn't run through canonicalization no need to reattach units to lits.

Fix: Non-Canonicalized get wrong units

---

src/atopile/buildutil.py
src/faebryk/exporters/pcb/testpoints/testpoints.py

Exporter for testpoint location and information. Can be used for bed-of-pins, other test hardware setups and flying probe testing.
Example JSON output
```json
{
"TP1": {
"testpoint_name": "output_voltage_feedback.resistor_control_loop_measurement.testpoint[0]",
"net_name": "output_voltage_feedback-contact-1",
"footprint_name": "TestPoint:TestPoint_Pad_D1.0mm",
"position": {
"x": 3.5,
"y": -10.0,
"rotation": 180.0
},
"layer": "B.Cu"
},
"TP2": {
"testpoint_name": "output_voltage_feedback.resistor_control_loop_measurement.testpoint[1]",
"net_name": "output_voltage_feedback-contact",
"footprint_name": "TestPoint:TestPoint_Pad_D1.0mm",
"position": {
"x": -0.25,
"y": -10.0,
"rotation": 180.0
},
"layer": "B.Cu"
}
}
```

Exporters: PCB: Add testpoint location and information

---

.github/workflows/docs.yml

This seems way overcomplicated and I didn't manage to get it working. Stuff it, insecure docs are better than undeployable docs

Disable security for github pages deployment

---

src/atopile/cli/create.py

Honestly more hacks around it but 🤷‍♂️
```
(atopile) hil_tester % ato create build-target
faebryk is installed as editable package, compiling c++ code
[10:31:13] WARNING  Your version of atopile (0.3.17) is out-of-date. Latest version: 0.3.23.                                                                                                                                                         
You can find upgrade instructions here: https://atopile.io/#installation                                                                                                                                                         
INFO     Using project /Users/mattwildoer/Projects/atopile-workspace/atopile/tmp/hil_tester …
```

Fixes 1131: Unfriendly error on poor module name

---

src/atopile/buildutil.py
src/faebryk/core/node.py
src/faebryk/exporters/pcb/kicad/transformer.py
src/faebryk/library/has_descriptive_properties.py
src/faebryk/libs/app/picking.py
src/faebryk/libs/util.py

Dump parameter aliases of picked modules to pcb attributes, so when building with `--keep-picked-parts` we can load the values for verification.

Fix: Save & Load params

---

src/faebryk/libs/sets/sets.py

Frozen builds were failing due to order of serialized params changing, adds sorting of elements to keep consistent between builds.

sort elements in enum before serializing to fix frozen build changing

---

pyproject.toml
uv.lock

Update scikit to newest version by forking it to disable the editable check

Build: Update nanobind & scikit-build

---

src/faebryk/libs/picker/api/picker_lib.py

Quick fix to print out the module where the exception is coming from.
Before:
After:
Might be worth to have a look at how `ExceptionGroup` is being printed by the logger. It currently does not use the `__repr__` or `__str__` of the errors in the group, so a lot of the info is missing. 

Add module name to PickError

---

src/atopile/attributes.py
src/atopile/buildutil.py
src/faebryk/library/_F.py
src/faebryk/library/requires_external_usage.py
src/faebryk/libs/app/checks.py
test/front_end/test_front_end.py
test/libs/test_checks.py

Checks if ModuleInteface is used outside of module it's residing in. See testcase for more explanation.
Ato: Add `.requires = True`
Library: Add `requires_external_usage` trait

Libs: Checks: Add requires external usage

---

src/faebryk/libs/app/checks.py
test/libs/test_checks.py

Root modules can't have external usage by definition.
Disable check for those.

Libs: Checks: Disable external check if root module

---

src/atopile/front_end.py

---
This pull request updates error handling in the `visitConnectable` method of `src/atopile/front_end.py` to replace assertions with user-friendly error messages. This change improves the robustness and clarity of error reporting for invalid `ModuleInterface` connections.
* Replaced `assert` statements with `UserTypeError` exceptions to provide detailed error messages when a node is not a `ModuleInterface`. The error messages include the context and a traceback for easier debugging.

Ato: Better error for attempted non-mif connection

---

src/faebryk/library/requires_external_usage.py

Required was failing builds for packages where the interfaces cannot be connected to externally because there is no module one level up.
Now checks for parent.parent of a MIF, if none, disables check

Disable required check for top level modules

---

src/faebryk/libs/app/picking.py

When swapping out a component for one that didnt have matching param names (in my case a buck converter ic) would get an error. Now we ignore params from the PCB that dont have a corresponding param in the design.

ignore parameters from modules that dont exist any more

---

src/faebryk/library/requires_external_usage.py

Reordered function to first check if the required item is located in the top level module, if so, ignore the check.
Fixes issue where there are no connections with i2c interface, as connections are directly to pins.

Fix: Checks: Required: Reorder

---

src/atopile/buildutil.py
src/atopile/cli/build.py
src/atopile/config.py

@jrhrsmit made this nice feature, but it was not accessible at the build process

Buildutil: Enable `hide_designators` option

---

src/atopile/attributes.py
src/faebryk/library/Capacitor.py

- prevented `requires_external_usage` checks to trigger

Fix: Don't shim floating powers in cap

---

src/atopile/parse.py

CLI: Improve formatting for syntax errors

---

src/faebryk/library/Regulator.py

Adds bridgeable trait to base definition of regulator, which allows you to do:
power_in ~> regulator ~> power_out
Which is pretty nice!

Library: Add bridgable trait to regulator

---

.github/dependabot.yml

Doesn't do anything useful at the monent due to
- lacking uv.lock support
- can't run pytest (some aws credential problem)

CI: Disable dependabot

---

src/atopile/cli/create.py

Switched Manufacturer & Part no
```
❯ ato 'create' 'part' '--search' 'C2688883'                  
[16:13:54] INFO     Using project /home/needspeed/workspace/atopile/examples/ch3_0_simple_led                                                                                                              
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━┓
┃ Manufacturer ┃ Part Number  ┃ Description                     ┃ Supplier ID ┃ Stock ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━┩
│ NXP Semicon  │ PCA9536D,118 │ 400kHz SO-8  I/O Expanders ROHS │ C2688883    │ 5     │
└──────────────┴──────────────┴─────────────────────────────────┴─────────────┴───────┘
```

Fix: CLI part create table titles

---

src/faebryk/exporters/netlist/graph.py
test/end_to_end/test_pcb_export.py

If mif connected without parent was still undeterministic.
- also fixed '-0' not being appended in duplicates

Fix: Net names determinism

---

src/faebryk/exporters/parameters/parameters_to_file.py

Include the parameters of the root modules in the parameter export
Do not only export the parameters of the modules within a module, but also the parameters of the module itself.

Exporter: Parameters: Include root module parameters in export

---

src/vscode-atopile/src/ui/buttons.ts

Create project was expecting a build target, which doesnt make much sense. Now uses _runInTerminal instead which has fixed the behavior for me.
Also updated the buttons for shell and create project such that they are visible even if there is no ato project in your editior.

Fix: create project

---

src/vscode-atopile/README.md

VSCode extension docs were wrong and bad, had claude type something up. Appears to be less wrong and looks kinda nice.

Docs: tidy up vscode extension docs and remove extension gif

---

src/faebryk/libs/kicad/paths.py

The `ato create` command was hanging on systems with large home directories due to a recursive glob search from `~`. 
**What changed:**
- Check common directories first (`.local`, `.config`, `Documents`, `Library`, `AppData`) 
- Fall back to full home search only if needed
- Same functionality, just faster for most users
**Result:**
- Commands that hung now complete in ~1 second
- Still finds KiCad in unusual locations via fallback

Fix hanging when searching for KiCad plugins

---

src/atopile/front_end.py

`typing.get_type_hints(callable_)` is called twice; once in `_try_upgrade_str_to_enum` and once on the deleted line.
This fixes the model build of the reg - though it now fails on a "no data error w/ LCSC" (out of scope)

Patch bug introduced breaking templated type-hints in 0.11.2

---

src/faebryk/exporters/netlist/graph.py
src/faebryk/library/Addressor.py
src/faebryk/library/Battery.py
src/faebryk/library/CAN.py
src/faebryk/library/CapacitorElectrolytic.py
src/faebryk/library/DifferentialPair.py
src/faebryk/library/Diode.py
src/faebryk/library/ElectricPower.py
src/faebryk/library/EnablePin.py
src/faebryk/library/Ethernet.py
src/faebryk/library/HDMI.py
src/faebryk/library/I2C.py
src/faebryk/library/I2S.py
src/faebryk/library/JTAG.py
src/faebryk/library/MOSFET.py
src/faebryk/library/MultiSPI.py
src/faebryk/library/PDM.py
src/faebryk/library/ResistorVoltageDivider.py
src/faebryk/library/SPI.py
src/faebryk/library/SWD.py
src/faebryk/library/UART.py
src/faebryk/library/UART_Base.py
src/faebryk/library/USB2_0_IF.py
src/faebryk/library/USB_C.py
src/faebryk/library/XtalIF.py
src/faebryk/library/_F.py
src/faebryk/library/has_net_name_affix.py
test/end_to_end/test_net_naming.py
test/test_cli.py
test/test_examples.py

This PR improves net naming and adds differential pair support:
Introduces suggested net names in ato (suggest_net_name) that strongly influence naming while deconflicting.
Adds required net name affixes (prefix/suffix) for cases like differential pairs.
Refines the net naming algorithm: better deconfliction, no leading dashes, and smarter base-name selection.
- Add suggest_net_name setter in src/atopile/attributes.py using F.has_net_name(Level.SUGGESTED).
- Net naming algorithm updates (src/faebryk/exporters/netlist/graph.py)
- Respect suggested and expected names as hints/requirements.
- Avoid leading “-” when no prefix is present.
- Prefer interface instance name for conflict prefixing.
- Support required affixes via F.has_net_name_affix; affixes are concatenated directly to the base …

Library: Add suggested net names

---

src/faebryk/library/JTAG.py
src/faebryk/library/SWD.py

- add missing RTCK (return clock) interface to JTAG
- makes the ato examples of JTAG and SWD a bit better/more clear
Needed the missing interface in JTAG.

Library: JTAG/SWD: Add better example, add missing interface

---

src/atopile/front_end.py
src/atopile/lsp/lsp_server.py
test/test_lsp_completion.py

Fix go-to-definition in LSP for `new <Type>` and `<field_ref>` (e.g resistor[0]).
Those two are the most useful cases for go-to because they jump across files.
- only in blocks (not in imports)
- no tests
- no modules & interfaces (no params)
- fabll typeref only (no fieldref)

LSP: Fix 'go to definition' (mvp)

---

src/vscode-atopile/src/common/file-resource-watcher.ts

Fixes repeated `ENOENT` errors in "Window" output pane. Occurs e.g. when a layout file path is implied by a manifest but hasn't yet been created.

VSCE: Fix `stat` on non-existent watched files
