atopile/atopile

- README.md
Revised and fixed typos.
Also added some dot points to more quickly communicate the design intent of this project.
> Reviewed and revised README.md for spelling and clarity

- src/atopile/nets.py
> Top level only Netname algorithm

- src/atopile/cli/cli.py
- src/atopile/cli/configure.py
New users will be presented with the following:
> Ask users permission to configure

- src/atopile/cli/install.py
> Improve error if the version spec doesn't match anything

- src/atopile/cli/install.py
Fixes this: https://github.com/atopile/atopile/issues/126
> ato install --jlcpcb finds root dir with ato.yaml

- src/atopile/cli/create.py
- src/atopile/config.py
https://www.loom.com/share/1cf3a53252fc4331a661f210fc040fcf
> build configs working

- src/atopile/config.py
> Revert "Upgrade default component server"

- src/atopile/assertions.py
- src/atopile/cli/build.py
- src/atopile/cli/common.py
- src/atopile/cli/inspect.py
- src/atopile/front_end.py
- src/atopile/instance_methods.py
- src/vscode-atopile/syntaxes/ato.tmLanguage.json
- tests/test_assertions.py
> Add assertions target

- src/atopile/errors.py
> Always handle ato errors when muffling fatailities

- docs/first_project.md
* remove duplicate `src` directory
* replace `├── file.ato` with `└── file.ato`
> Remove duplicate src directory from project tree

- src/atopile/cli/install.py
- src/atopile/config.py
running `ato install` from a child repo would crash. This should fix it.
> Fix path on `ato install`

- src/vscode-atopile/package.json
- src/vscode-atopile/snippets/snippets.json
- src/vscode-atopile/src/extension.ts
- src/vscode-atopile/src/ui/ui.ts
Adds commands, statusbar buttons, and snippets to VS Code.
> First UI commit

- src/atopile/components.py
- src/atopile/instance_methods.py
Zero-diff on artifacts 
```bash
(.venv) swoop % diff -r build build-old
(.venv) swoop % 
```
Designators change
> Add instance_methods.get_data

- README.md
> docs: pardiagrams => paradigms

- pyproject.toml
- src/atopile/cli/common.py
- src/atopile/cli/create.py
- src/atopile/cli/install.py
- src/atopile/config.py
- src/atopile/errors.py
- src/atopile/utils.py
- tests/test_config.py
https://toil.kitemaker.co/2hAmxC-atopile/dSlNKj-atopile/items/110
> Break dependency links by default

- src/atopile/cli/create.py
> fixed path, was trying to save ato file to elec/src/elec/src

- src/atopile/config.py
Upgrading to latest component server
> upgrade component server

- docs/config.md
- src/atopile/cli/build.py
- src/atopile/config.py
- src/atopile/manufacturing_data.py
> Add DRCs to KiCAD build

- src/atopile/assertions.py
- src/atopile/parse_utils.py
- tests/test_parse_utils.py
Currently, debugging to-tight of a constraint really sucks. This at least gives you a fighting chance
Closes #320
> Add more debug information to assertions

- src/atopile/viewer/src/App.tsx
- src/atopile/viewer/src/BlockDiagramApp.tsx
- src/atopile/viewer/src/SchematicApp.tsx
Somehow the `<ReactFlowProvider>` tag needs to be wrapped in another object for the fit view function to execute properly.
> Fix relayout after component reload

- src/atopile/kicad_plugin/common.py
- src/atopile/kicad_plugin/pullgroup.py
- src/atopile/kicad_plugin/pushgroup.py
Closes #397 
I've tested it locally and it does bring in the drawing layer:
from:
> feat(kicad): update kicad plugin to support pull/push of DRAWINGS

- src/atopile/cli/cli.py
- src/atopile/cli/install.py
- src/atopile/telemetry.py
> Fix `ato create`

- README.md
- docs/development.md
- mkdocs.yml
- src/vscode-atopile/README.md
> Fix links in docs

- src/atopile/cli/install.py
> Fix linked dependency re-install after breaking links

- src/atopile/manufacturing_data.py
When attempting to build the "all" target on windows with `ato build --target all`, you will get the error at the bottom.
This is because the `find_kicad_cli` function does not support locating kicad on Windows.
After adding a simple implementation, which I've tested on Windows w/ KiCad 8.0, the build appears to complete successfully.
Error:
```
[16:20:16] INFO     Building 'mfg-data' for 'default' config                                                                                                                                                                                                                        build.py:96  + Exception Group Traceback (most recent call last):
|   File "<frozen runpy>", line 198, in _run_module_as_main
|   File "<frozen runpy>", line 88, in _run_code …
```
> Add support for finding kicad-cli on Windows

- src/atopile/cli/inspect.py
Add `--dump-csv <file.txt>` to dump a CSV to a file
> Dump inspection output to a CSV

- docs/how-to.md
- docs/install.md
> Add how-to on installing footprints

- src/atopile/bom.py
- src/atopile/components.py
> add price to BOM output

- src/atopile/kicad6.j2
- src/atopile/kicad6_datamodel.py
- src/atopile/netlist.py
Pipe the `do_not_populate` and `exclude_from_bom` properties through to the generated netlist.
> Add dnp and exclude_from_bom to exported netlist

- src/atopile/kicad_plugin/common.py
- Assign zone net on assignment
- Assign copied footprints to correct layer
(There's still some funky behavior when importing really complex layouts, but this is a step in the right direction, I think)
> KiCad layout importing fixes

- docs/kicad.md
Had to look through the code to figure out how to add the plugin to KiCad, added a quick note in the documentation if someone else has the same issue.
> nit: Add note in docs if issue wrt kicad plugin installation

- src/faebryk/libs/logging.py
> Warnings are yellow

- pyproject.toml
- test/libs/picker/test_pickers.py
Mark slow tests as slow and not run by default
> Perf: Mark slow tests

- src/faebryk/libs/picker/api/picker_lib.py
Improve missed picks on the API by including params that were tried
> Picker: Better missed pick errors including params

- src/atopile/cli/build.py
- src/atopile/errors.py
- src/atopile/telemetry.py
> CLI: print non-ato group exception tracebacks on exit

- .gitattributes
See https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
> Repo: Add gitattributes generated mark to KiCAD files

- examples/project/.ato/modules/generics/README.md
- src/atopile/_shim.py
- src/atopile/front_end.py
- src/faebryk/libs/app/erc.py
- src/faebryk/libs/exceptions.py
- test/libs/test_exceptions.py
- test/test_front_end.py
> DSL: Improve shimming and connection - ESP32-S module builds

- src/atopile/parser/__init__.py
- src/faebryk/core/cpp/__init__.py
- src/faebryk/libs/util.py
Automatically rebuild ato's grammar on import with an editable install
> Tooling: auto-rebuild grammar files w/ uncommited changes

- src/atopile/bom.py
Allow creation of BOM when a part has no MPN and hence no price.
Fixes #595 
By submitting this issue, you agree to follow our [Code of Conduct](/faebryk/faebryk/blob/main/docs/CODE_OF_CONDUCT.md):
> Fix BOM price error when no MPN

- src/atopile/front_end.py
> DSL: Improve attribute errors on the front-end

- src/faebryk/libs/examples/buildutil.py
- test/test_examples.py
> Fix and test examples

- .github/CODEOWNERS
Fix global rule
Add subdirectories: faebryk, core, stdline, picker, ato dsl
> Meta: Fix and granularize CODEOWNERS

- src/faebryk/libs/logging.py
- test/core/cpp/test_importcpp.py
- test/core/solver/test_solver.py
- test/core/test_core.py
- test/core/test_hierarchy_connect.py
- test/core/test_parameters.py
- test/core/test_performance.py
- test/exporters/pcb/kicad/test_pcb_transformer.py
- test/importers/netlist/kicad/test_schematic_kicad.py
- test/integration/netlist/kicad2faebryk/test_netlist_kicad_2_faebryk_prj.py
- test/library/test_footprints.py
- test/library/test_names.py
- test/libs/test_lcsc.py
- test/libs/test_util.py
- test/libs/test_util_atexit.py
- test/runtest.py
Removes need for `__name__  == __main__` boilerplates to run individual test.
> Test: Add test runner

- src/faebryk/libs/util.py
I don't think we need to handle case sensitivity yet, but it could be problem in the future
I didn't see a good way to do this with `pathlib`
> Make layout mapping case-insensitive

- test/core/test_mif_connect.py
> Test: Add regression tests for incompat mifs

- src/atopile/buildutil.py
Don't rewrite PCB if we haven't changed anything
> Backup PCB on rebuild

- src/faebryk/core/solver/defaultsolver.py
> Core: Raise solver timeout

- src/atopile/buildutil.py
> Reload PCB after applying netlist

- test/test_cli.py
> Fix CLI tests

- src/atopile/cli/cli.py
- src/atopile/cli/configure.py
Fixes: #656
1. `ato configure` explicitly (w/ more output)
2. `ato build` -> implicit configure, less logging
> Install KiCAD Plugin on at least some more Linux OSs

- src/faebryk/libs/sets/numeric_sets.py
> Bugfix: Numeric_Interval.as_center_rel

- src/atopile/cli/logging.py
- src/atopile/errors.py
- src/atopile/parse_utils.py
- src/atopile/parser/AtoLexerBase.py
- test/test_parse_utils.py
> Even better errors 🤤 - coloured, syntax highlighted printout in the terminal

- src/faebryk/core/solver/defaultsolver.py
> Core: Set solver timeout to 120s

- README.md
- dockerfiles/Dockerfile.kicad
- pyproject.toml
- src/faebryk/libs/util.py
- uv.lock
I realized I'd kindly left myself markers around to make this easier. Upgarding those points now
> Python3.13: 2 - Electric Boogaloo

- src/atopile/cli/cli.py
- src/atopile/cli/logging.py
> Add tracebacks for UserErrors with verbosity flags

- src/faebryk/exporters/pcb/kicad/transformer.py
Ported from https://github.com/atopile/faebryk/pull/91
> Add basic add_group function from faebryk pr #91

- .github/workflows/regression.yml
- .gitignore
- pyproject.toml
- uv.lock
> Log regression testing history

- src/faebryk/exporters/pcb/kicad/pcb.py
- src/faebryk/libs/kicad/fileformats.py
> Fix: Double UUID Pad bug

- examples/ch2_5_signal_processing.py
- src/faebryk/core/parameter.py
- src/faebryk/core/solver/utils.py
- src/faebryk/library/FilterElectricalLC.py
- src/faebryk/library/FilterElectricalRC.py
Parameter deduction is incorrect, but now it builds
> Fix: Examples: Fix build of signal processing

- src/atopile/front_end.py
- src/faebryk/core/parameter.py
- src/faebryk/core/solver/analytical.py
- src/faebryk/core/solver/canonical.py
- src/faebryk/core/solver/literal_folding.py
- src/faebryk/core/solver/utils.py
- test/core/solver/test_solver.py
Adds Min/Max and canonicalizations
Also:
- Add Integrate/Differentiate
- Use Min/Max in ato frontend
> Core: Add Min/Max Expressions

- src/atopile/front_end.py
- src/faebryk/libs/exceptions.py
- test/libs/test_exceptions.py
Move errors to the end of the log, and suppress duplicate warnings
> Make `ato` build again - Part 7: Diamonds Are Forever

- examples/.ato/modules/generics/capacitors.ato
- examples/.ato/modules/generics/resistors.ato
- src/atopile/_shim.py
- src/atopile/front_end.py
- src/faebryk/core/module.py
- src/faebryk/libs/exceptions.py
- test/libs/test_exceptions.py
> Make `ato` build again: Part 8 - The Dark World

- src/atopile/buildutil.py
- src/faebryk/exporters/pcb/kicad/pcb.py
As in the case of a `--standalone` regression build
> Improve errors for missing global footprint lib

- .github/workflows/pytest.yml
- .github/workflows/regression.yml
- src/faebryk/core/cpp/__init__.py
- src/faebryk/libs/util.py
- test/test_cli.py
- test/test_errors.py
- test/test_regressions.py
This should improve log-readability
> Increase rich console width for pytest and regression workflows

- src/atopile/buildutil.py
- src/atopile/cli/build.py
- src/atopile/config.py
- test/test_regressions.py
This helps with regression testing and is critical in CI
> Add frozen flag to force zero-diff on PCB

- src/faebryk/libs/util.py
Simple util. Want it elsewhere
> Add try_relative_to util for cleaner path logging

- src/faebryk/library/has_descriptive_properties_defined.py
> Fix: Descriptive Properties on change

- src/atopile/_shim.py
- src/atopile/front_end.py
> Add basic DNP and exclude from BoM support

- src/atopile/_shim.py
- src/faebryk/core/node.py
- src/faebryk/libs/picker/picker.py
- test/front_end/test_front_end_pick.py
- Fixes footprint candidate shim
- Fixes picking trait
> Fix: Frontend: Pick caps

- .github/workflows/regression.yml
- pyproject.toml
- test/test_regressions.py
- uv.lock
The `ato create project` changes are in there because I needed `robustly_rm_dir`
> Save failed regression artifacts

- src/atopile/buildutil.py
- src/atopile/cli/build.py
- src/atopile/config.py
- src/faebryk/exporters/netlist/graph.py
- src/faebryk/exporters/pcb/kicad/transformer.py
- src/faebryk/library/Net.py
- src/faebryk/libs/app/pcb.py
> Load net names from PCB, making frozen stable!

- src/atopile/_shim.py
- src/faebryk/exporters/netlist/graph.py
- src/faebryk/library/ElectricPower.py
- test/front_end/test_front_end.py
Net names were colliding, which was causing all varieties of strange behaviour in KiCAD. 
Fix that
> Fix net name collisions

- src/faebryk/exporters/pcb/kicad/transformer.py
- src/faebryk/libs/kicad/fileformats.py
This appears to fix unfilled zones
@napowderly can you confirm the zone causing trouble was unfilled?
> Fix zones without fill

- src/faebryk/exporters/pcb/kicad/transformer.py
change footprint to atopile address to make message clearer
> change footprint to atopile address, make message clearer

- src/atopile/buildutil.py
- src/atopile/errors.py
- src/atopile/front_end.py
That don't yet have a good solution to debug, with TODOs to re-upgrade them at a later time
> Downgrade warnings

- test/test_regressions.py
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> comment out nonos from regression tests

- .cursorrules
Decisions:
- Markdown formatting. It's clear and concise
- Sections per general "hat" we may wear (eg. testing)
Extension:
- What keywords are available for things like "run" etc...
> Add base .cursorrules

- .github/workflows/pytest.yml
https://github.com/pytest-dev/pytest-github-actions-annotate-failures
> Add `pytest-github-actions-annotate-failures` for CI

- src/atopile/config.py
> Set default ["paths"] to dict if missing in config

- src/faebryk/exporters/pcb/kicad/transformer.py
…without checking their names. 
I don't know how the name and numbers would've possibly got out of sync, but this seems to have fixed it reliably
> Update nets based solely on number

- src/atopile/cli/install.py
- src/atopile/config.py
Sensible errors when running commands outside of project for `ato install`
> Fix config outside of project and on installs

- src/atopile/errors.py
- src/atopile/front_end.py
- src/atopile/parse.py
- src/atopile/parse_utils.py
- test/front_end/test_front_end.py
- test/test_parse.py
- Update `errors.py` to use token-based source tracking instead of context-based
- Modify `parse_utils.py` to support token-based lexer reconstruction
- Simplify error listener in `parse.py`
- Add test for syntax error handling
- Improve error message generation and source code highlighting
> Fix SyntaxError tracebacks and refactor error handling and token-based source tracking

- src/atopile/kicad_plugin/__init__.py
- src/atopile/kicad_plugin/common.py
- src/atopile/kicad_plugin/pushgroup.py
- src/atopile/kicad_plugin/reloadgroup.py
- src/atopile/layout.py
Currently, this just supports syncing the layout of the top-level module.
I implemented nesting modules and synced them as well. However, it crashed KiCAD and debugging that was impractical and not the best use of time. I've left the stubs of that work for the future
Additionally, this fixes logging and adds logs to pull, push and reload groups
> Fix syncing with nested layouts

- src/faebryk/libs/app/pcb.py
@sam-mellor his the same issue you were, and managed to fix it
> Fix footprint lib creation with a build with dir spec'd

- src/faebryk/core/parameter.py
- src/faebryk/core/solver/canonical.py
- src/faebryk/core/solver/defaultsolver.py
- src/faebryk/core/solver/literal_folding.py
- src/faebryk/core/solver/utils.py
- src/faebryk/library/M24C08_FMN6TP.py
- src/faebryk/libs/sets/numeric_sets.py
- src/faebryk/libs/sets/quantity_sets.py
- src/faebryk/libs/sets/sets.py
- test/core/solver/test_solver.py
- test/core/solver/test_solver_util.py
- Decanonicalize Set Difference
- Fix bugs in Tree unit check
- Sets: implement difference, symmetric\_difference, round, abs, log, sin, lt, gt
- add pure lit fold tests
> Core: Solver implement pure literal fold

- src/atopile/cli/cli.py
- src/atopile/cli/create.py
- src/atopile/config.py
> Fix `ato create build-target`

- src/atopile/cli/create.py
- fix return type
- fix designator prefix
- use has_designator_prefix.Prefix if possible
- fix LCSC id
- separate code blocks
> CLI: Fix create component fabll

- dockerfiles/Dockerfile.kicad
- src/atopile/cli/cli.py
- src/atopile/cli/create.py
- test/test_cli.py
- test/test_create.py
- test/test_errors.py
- test/test_examples.py
- test/test_regressions.py
> Fix `ato create project`'s name and improve help

- test/test_regressions.py
- Runs regression tests without `--frozen` flag
- `xfail` on PCB file modifications
Enables distinguishing between complete build failures and successful builds with artifact modification.
> Test: run regression tests without `--frozen`

- .github/workflows/vsx.yml
Adds 1000 to patch version rather than using semver dev releases
> Fix vscode extension deployment

- src/atopile/cli/build.py
- src/atopile/cli/install.py
When in non-interactive mode, we don't offer install and continue after warning
When interactive, we ask if you want to install and continue regardless
Fixes: #927
> Hint `ato install`

- src/faebryk/libs/app/erc.py
- test/core/test_mif_connect.py
Fixes: #897
A massive further improvement would be to add the lines which caused the issue, however without the ability to add traits to connections, which is a whole other can of worms, this isn't easy, and this is already an enormous step up
> Improve ERC messages

- src/faebryk/libs/app/designators.py
- uv.lock
Stole this fix from @iopapamanoglou :sweat_smile: 
https://github.com/atopile/atopile/issues/843#issuecomment-2601783191
> Bugfix: Designator prefix overwrite

- src/atopile/buildutil.py
- src/faebryk/libs/exceptions.py
- src/faebryk/libs/picker/api/models.py
- src/faebryk/libs/picker/api/picker_lib.py
- src/faebryk/libs/picker/picker.py
- test/libs/picker/test_pickers.py
- test/libs/test_exceptions.py
- Raises an exception group of `PickError`s in the case of a server failure
- Adds `iter_leaf_exceptions` as a helper to flatten `ExceptionGroup`s
- Adds params to error output
> `PickError` improvement

- src/atopile/cli/install.py
- src/atopile/config.py
Switches to new package registry implementation. Fixes sporadic issues with package installation.
> CLI: Update package registry URL

- pyproject.toml
- src/atopile/cli/create.py
- test/test_create.py
- uv.lock
- Use cookiecutter for a project template
- Change workflow slightly for project creation and cloning
- Theoretically much better support other project templates, and configuration from within the template itself.
- Project template https://github.com/atopile/project-template/tree/compiler-v0.3
> Branch for project template

- test/test_regressions.py
- This may have an impact on the performance of the regressions
- We end up with full profiles for them to make them faster
- Benchmark doesn't work with xdist
> Switch benchmarking for profiling via pyinstrument

- src/faebryk/libs/sets/numeric_sets.py
- src/faebryk/libs/sets/quantity_sets.py
- test/libs/test_sets.py
- Use decimals for the internal storing and calculations
- Remove int intervals, since they were not really used and probably buggy
> Sets: Switch to decimals; Remove int sets

- src/faebryk/library/BH1750FVI_TR.py
- src/faebryk/library/HLK_LD2410B_P.py
- src/faebryk/library/ME6211C33M5G_N.py
- src/faebryk/library/SCD40.py
- src/faebryk/library/TXS0102DCUR.py
- src/faebryk/library/XT30PW2plus2.py
- src/faebryk/library/_F.py
> Bugfix: faebryk: Library: Add missing descriptive properties

- uv.lock
We should publish this properly, so we can better manage versions. This will have to do for the second
> Upgrade `pytest-history` version

- examples/ch1_2_good_voltage_divider.ato
- src/atopile/kicad_plugin/common.py
- src/atopile/kicad_plugin/pullgroup.py
- src/atopile/kicad_plugin/reloadgroup.py
Problem: Tracks and vias not updaing nets correctly when importing layout
Fix:
-Refactor net matching from zone update function to create a soruce-> target net map
-Use map in sync_track to manually update net name
-Better error messages
> Manual track net name sync when loading layout blocks

- src/faebryk/library/NetTie.py
- src/faebryk/library/_F.py
From: https://github.com/atopile/faebryk/pull/39
Co-authored-by: @mawildoer 
> Library: Add NetTie to library

- .github/dependabot.yml
More annoying than useful at the moment.
Need to figure out updating uv.lock etc.
See #1036
> Meta: Disable dependabot

- examples/ch2_8_mcu.py
- src/faebryk/library/USB_C_PSU_Vertical.py
At least it is working now. Should later be merged with the other usb PSU designs into 1 good module
> Library: USB PSU: Make the module slightly less bad

- src/faebryk/libs/picker/picker.py
Vibe picking was causing problems with solver. Need to rip it out until it is more thought though.
> Disabling fast picking, not working and causing problems

- src/atopile/config.py
- src/faebryk/libs/app/designators.py
- Duplicate designator check failing 
- Frozen not correctly checking conflicting options
> Fix frozen flag

- src/atopile/front_end.py
> Front end: Add descriptive user error to get param

- src/faebryk/core/solver/defaultsolver.py
- src/faebryk/libs/picker/picker.py
- src/faebryk/libs/util.py
- test/core/performance/test_performance_pick.py
> Core: Solver speed: Parallel slow pick

- src/atopile/errors.py
- src/atopile/front_end.py
- src/faebryk/core/moduleinterface.py
> Ato: Improve error for invalid connections

- examples/ch1_2_good_voltage_divider.ato
- examples/ch2_8_mcu.py
- test/test_examples.py
Update examples to make them build, use library vdiv and use explicit pick for led, remove xfail marks
> Update examples to make them build

- src/faebryk/core/solver/mutator.py
- src/faebryk/core/solver/symbolic/pure_literal.py
- src/faebryk/core/solver/symbolic/structural.py
- src/faebryk/core/solver/utils.py
- src/faebryk/libs/picker/picker.py
- test/core/solver/test_solver_util.py
- test/front_end/test_front_end_pick.py
- test/libs/picker/test_pickers.py
- more eager folding (lit & pure lit expr)
- merge subsets with mutation
> Core: Solver fix loop vdiv

- src/atopile/cli/cli.py
- src/atopile/config.py
Reverts atopile/atopile#1085
Fixes #1089
> Revert "CLI: Defer creating layout file for build until build context is activated"

- src/faebryk/library/TestPoint.py
- src/faebryk/library/_F.py
Add basic test-point support based on KiCad footprints.
> Library: Add: Add testpoint

- docs/guides/installation.md
- docs/quickstart.md
@iopapamanoglou you might want to add arch linux instructions too?
> Improve install instructions

- src/faebryk/exporters/pcb/kicad/artifacts.py
See https://docs.kicad.org/9.0/en/cli/cli.html
> Generate all layers

- src/faebryk/library/is_bus_parameter.py
Attempted workaround that just ignores mif bug
> Fix: Workaround mif bug, bus params

- src/atopile/buildutil.py
G becomes invalid when modified, need to update the reference.
Fixes `Trait has_designator not found` errors.
> Fix: Buildutil: Use most recent Graph

- pyproject.toml
- src/atopile/cli/build.py
- src/atopile/cli/create.py
- src/atopile/cli/install.py
- src/atopile/telemetry.py
- test/conftest.py
- uv.lock
Duplicate (for now) telemetry over to Posthog
> Add Posthog Telemetry

- src/atopile/config.py
Before:
After:
Fixes  issue mentioned by tiedan2020 in discord
> Add: deprecation message/error for ato-version

- src/atopile/cli/install.py
- src/faebryk/libs/project/dependencies.py
- src/faebryk/libs/util.py
- allow removing (but not uninstall) in use dependencies
- list all root nodes
> Fix: CLI: ato remove/list

- pyproject.toml
- src/atopile/buildutil.py
- src/faebryk/libs/app/checks.py
- src/faebryk/libs/kicad/drc.py
- src/faebryk/libs/kicad/fileformats_latest.py
- src/faebryk/libs/util.py
- test/libs/util/test_md_list.py
- uv.lock
Use kicad-cli internally
Only run if mfg-data target
> Libs: Checks: Add DRC checks

- test/test_regressions.py
> Fix: Tests: Build regressions

- src/atopile/cli/create.py
> Fix `ato create component` for pins which are named as numbers

- src/atopile/buildutil.py
- src/atopile/config.py
- src/faebryk/core/trait.py
- src/faebryk/library/I2C.py
- src/faebryk/library/PCB.py
- src/faebryk/library/_F.py
- src/faebryk/library/has_solver.py
- src/faebryk/library/implements_design_check.py
- src/faebryk/library/requires_external_usage.py
- src/faebryk/library/requires_pulls.py
- src/faebryk/libs/app/checks.py
- src/faebryk/libs/app/erc.py
- test/library/nodes/test_addressor.py
- test/library/test_design_checks.py
- test/libs/test_checks.py
- More modular checks
- Attach PCB & Solver to App
- config: exclude_checks
- better log separation
Depends on #1140
> Libs: Checks: Allow exclude

- src/atopile/buildutil.py
Frozen check was comparing the wrong thing.
> Fix frozen file comparison

- examples/ch2_1_fab.py
- src/faebryk/libs/picker/picker.py
Lines that backed up tree were too late.
> Fix: Run solver even if only explicit picks

- src/atopile/errors.py
- src/atopile/front_end.py
Refactors feature checks and ensure consistent messages.
> ato: Consistent error messages for experiments

- src/faebryk/library/Analog_Devices_ADM2587EBRWZ_ReferenceDesign.py
- src/faebryk/library/B0505S_1WR3.py
- src/faebryk/library/B0505S_1WR3_ReferenceDesign.py
- src/faebryk/library/CBM9002A_56ILG_ReferenceDesign.py
- src/faebryk/library/CH344Q.py
- src/faebryk/library/CH344Q_ReferenceDesign.py
- src/faebryk/library/FilterElectricalRC.py
- src/faebryk/library/INA228_ReferenceDesign.py
- src/faebryk/library/Mounting_Hole.py
- src/faebryk/library/RS485_Bus_Protection.py
- src/faebryk/library/ResistorArray.py
- src/faebryk/library/SNx4LVC541A.py
- src/faebryk/library/TECH_PUBLIC_USBLC6_2SC6.py
- src/faebryk/library/Texas_Instruments_SN74LVC541APWR.py
- src/faebryk/library/UART_RS485.py
- src/faebryk/library/USB2_0_ESD_Protection.py
- src/faebryk/library/_F.py
Mostly:
- cleaning up modules
- fixing some small bugs
- updating to latest way of doing things
- ato compatibility
- reference designs
- some cleaning
> Fix multiple library modules

- src/atopile/cli/cli.py
- src/vscode-atopile/syntax_examples.ato
- src/vscode-atopile/syntaxes/ato.tmLanguage.json
Updates `tmLanguage` grammar and adds `validate` command for syntax checking.
> VSCE: Update grammar for syntax highlighting

- src/atopile/cli/create.py
- src/faebryk/libs/github.py
- test/test_cli.py
Use GH to handle github calls
Make more optional
Fixes #1228
> Fix: ato create: Improve git workflow

- src/vscode-atopile/syntax_examples.ato
- src/vscode-atopile/syntaxes/ato.tmLanguage.json
Adds support for remaining scopes.
> VSCE: Enhanced syntax highlighting

- src/faebryk/libs/kicad/fileformats_latest.py
> Kicad file format: Fix pad zone connection

- src/atopile/config.py
- src/vscode-atopile/package-lock.json
- src/vscode-atopile/package.json
- src/vscode-atopile/src/common/findbin.ts
- src/vscode-atopile/src/common/server.ts
- src/vscode-atopile/src/ui/buttons.ts
- src/vscode-atopile/src/ui/example.ts
- src/vscode-atopile/src/ui/setup.ts
- fix powershell syntax for ato
- run lsp non-interactive so first time setup doesn't explode
- auto detect interactive if not set
- progress bar for install of uv
> Fix: VSCE: Run lsp non-interactive

- src/faebryk/libs/kicad/fileformats_latest.py
> KiCad file format: Fix dimension type and points

- src/faebryk/library/Crystal_Oscillator.py
Layout trait is currently just annoying, need to rethink how we do this
> Library: Remove layout trait from crystal oscillator

- src/faebryk/library/I2C.py
- test/library/nodes/test_addressor.py
Fix hack to include all hierarchy levels for bus detection
> Fix: I2C check: Isolated buses

- test/test_regressions.py
Remove HIL from regressions testing, moving useful stuff over to packages to have less to maintain.
> Test: Update test_regressions.py

- src/faebryk/libs/util.py
First cursor then fallback to code
> Fix: Prioritize cursor over code

- src/vscode-atopile/src/common/findbin.ts
- src/vscode-atopile/src/ui/buttons.ts
Alias ato in all new terminals and everytime the ato location changes
> VSCE: alias ato in all terminals

- src/atopile/cli/create.py
- src/faebryk/libs/ato_part.py
- src/faebryk/libs/logging.py
```bash
❯ ato 'create' 'part' '--search' 'C7501280' '--accept-single'
[09:51:52] WARNING  Your version of atopile (0.9.6) is out-of-date. Latest version: 0.9.7.
You can find upgrade instructions here: https://atopile.io/#installation
[09:51:53] INFO     Using project /home/needspeed/workspace/atopile/examples/ch3_0_simple_led
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━┓
┃ Manufacturer ┃ Part Number       ┃ Description                                                                                                                                ┃ Supplier ID ┃ Stock ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ …
```
> CLI: Print part import path

- src/atopile/buildutil.py
Else if_then_else not evaluated
> Fix: Run solver for frozen

- pyproject.toml
- src/faebryk/core/node.py
- test/libs/test_util.py
- uv.lock
> Fix: Core: Deterministic Node children

- src/faebryk/libs/codegen/atocodeparse.py
```
trait is_atomic_part<manufacturer="Nexperia", partnumber="PBSS5350X115", footprint="SOT-89-3_L4.5-W2.5-P1.50-LS4.1-TR.kicad_mod", symbol="PBSS5350X115.kicad_sym", model="SOT-89-3_L4.3-W2.5-H1.6-LS4.1-P1.50.step">
```
> Fix: AtoParser: Handle commas in trait strings

- src/faebryk/libs/app/picking.py
If part removed, no part in picked.
> Fix: PCB: Don't assume part for picked

- src/faebryk/library/is_auto_generated.py
- src/faebryk/libs/ato_part.py
- src/faebryk/libs/checksum.py
- src/faebryk/libs/kicad/fileformats_common.py
- remove \r
- replace multiple space (not indent)
- remove empty lines
- remove trailing space
> Fix: Stable file hashing

- src/faebryk/library/PDM.py
- src/faebryk/library/_F.py
Add PDM (pulse density modulation) interface commonly used with digital mems microphones
> Library: Add PDM interface

- src/faebryk/libs/kicad/fileformats_latest.py
> Fileformat: Less verbose rich

- src/vscode-atopile/syntaxes/ato.tmLanguage.json
Replace unicode char with degree symbol
> Fix: Syntax: Don't use unicode

- src/faebryk/libs/part_lifecycle.py
- src/faebryk/libs/util.py
- test/libs/test_util.py
- fix paths to 3dmodels of parts in packages
- disable global footprints
> Fix: 3Dmodels in packages

- src/faebryk/libs/part_lifecycle.py
> Fix: Error: LibNotFound

- src/vscode-atopile/resources/templates/rules/create_package.md
- src/vscode-atopile/resources/templates/rules/vibe_electronics.md
- src/vscode-atopile/src/common/llm.ts
add package and vibe coding instructions to .cursor rules
> VSCE: add package and vibe coding instructions to .cursor rules

- src/atopile/kicad_plugin/common.py
Fixes issue with syncing in macos (or anywhere else where symlinks are involved)
> Fix: KiPlugin: Sync path failure

- src/faebryk/library/regulators.ato
* Update variable names
* assert input voltage is power_in.voltage for default usage of load voltage requirements
* add docstrings
* constrain divider quiescent current to something reasonable until we can require parameters
> Library: Update Adjustable Regulator

- src/atopile/cli/cli.py
- src/atopile/cli/configure.py
- src/atopile/config.py
- src/faebryk/libs/paths.py
- move ~/atopile to config_dir
- auto setup (install kicad plugin)
Fixes #1370
> Setup: Move cfg dir & Auto-setup

- .gitignore
- currently annoying vsce creating them in ato-unrelated repo
> Meta: Ignore CLAUDE & .mcp

- examples/layout_reuse/.gitignore
- examples/layout_reuse/ato.yaml
- examples/layout_reuse/layout/sub/sub.kicad_pcb
- examples/layout_reuse/layout_reuse.ato
- pyproject.toml
- src/atopile/buildutil.py
- src/atopile/cli/build.py
- src/atopile/cli/configure.py
- src/atopile/kicad_plugin/pullgroup.py
- src/faebryk/libs/app/pcb.py
- src/faebryk/libs/kicad/fileformat_config.py
- src/faebryk/libs/kicad/ipc.py
- src/faebryk/libs/kicad/paths.py
- src/faebryk/libs/part_lifecycle.py
- src/faebryk/libs/util.py
- uv.lock
- clean up kicad path finding
- add kicad IPC
- enable multi open pcb
- add auto reload pcb
- backup every pcb (even if no changes)
- auto enable kicad ipc
> Build: Auto-reload PCB in KiCAD

- src/faebryk/library/FilterElectricalRC.py
- src/faebryk/library/_F.py
* Add can bridge trait to ElectricalFilterRC
* Add hardcode option to speed up compiler with many RC filters.
> Feature: Bridge and Hardcode RC Filter

- src/faebryk/library/FilterElectricalRC.py
* Remove unused hardcoded fc filter
> Fix: Remove unused harcode fc

- src/atopile/buildutil.py
Only if all elements in group are new in pcb
>  PCB: Automatically apply layout

- src/atopile/front_end.py
Was causing LSP to crash when building a graph for `has_part_picked`
> ato: Fix NameError on string to enum upgrade

- src/atopile/config.py
> CLI: Fix build generates a bunch of build dirs for dependencies
